import { chromium } from "@playwright/test";
const S = "/tmp/claude-1000/-home-madson-bina/0d4e4ab4-16f9-4d30-aa87-ceaf8555f442/scratchpad";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 } });
const errs = [];
p.on("pageerror", (e) => errs.push(String(e)));
p.on("console", (m) => m.type() === "error" && errs.push(m.text().slice(0, 120)));
await p.goto("http://localhost:3100/fa/login", { waitUntil: "networkidle" });
await p.fill('input[type="email"]', "e2e@example.com");
await p.fill('input[type="password"]', "inventory-test-password");
await p.click('button[type="submit"]');
await p.waitForTimeout(2500);
await p.goto("http://localhost:3100/fa/detect", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.screenshot({ path: `${S}/detect-fa.png` });
const keys = await p.evaluate(() => (document.body.innerText.match(/\b[a-z]+_[a-z_]+\b/g) || []).slice(0, 6));
console.log("raw keys:", JSON.stringify(keys));
console.log(errs.length ? "ERRORS: " + [...new Set(errs)].slice(0,4).join(" | ") : "no console errors");
await b.close();
