"""basemaps

Revision ID: 13de18a5b43a
Revises: a6cdce74dbef
Create Date: 2026-08-01 22:49:12.382206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13de18a5b43a'
down_revision: Union[str, Sequence[str], None] = 'a6cdce74dbef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basemaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url_template', sa.String(length=600), nullable=False),
    sa.Column('attribution', sa.String(length=300), nullable=False),
    sa.Column('tint', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basemaps_org_id'), 'basemaps', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basemaps_org_id'), table_name='basemaps')
    op.drop_table('basemaps')
    # ### end Alembic commands ###
