"""initial schema

Revision ID: 3bfaae047841
Revises: 
Create Date: 2026-07-28 13:10:36.542438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3bfaae047841'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The features table stores a PostGIS geometry column, so the extension has to
    # exist before the table is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('tile_count', sa.Integer(), nullable=False),
    sa.Column('failed_tile_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('run_tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('west', sa.Float(), nullable=False),
    sa.Column('south', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_tiles_run_id'), 'run_tiles', ['run_id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_feature_id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('source_value', sa.String(length=120), nullable=True),
    sa.Column('crop_path', sa.String(length=400), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_feature_id', name='uq_sign_per_job')
    )
    # GeoAlchemy2 emits the GiST index on geom as part of create_table, so
    # creating it here as well would fail with a duplicate relation.
    op.create_index(op.f('ix_signs_run_id'), 'features', ['run_id'], unique=False)
    op.create_index(op.f('ix_signs_source_feature_id'), 'features', ['source_feature_id'], unique=False)
    op.create_index(op.f('ix_signs_needs_review'), 'features', ['needs_review'], unique=False)
    op.create_index(op.f('ix_signs_class_name'), 'features', ['class_name'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_feature_id'), 'labels', ['feature_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_feature_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_signs_class_name'), table_name='features')
    op.drop_index(op.f('ix_signs_needs_review'), table_name='features')
    op.drop_index(op.f('ix_signs_source_feature_id'), table_name='features')
    op.drop_index(op.f('ix_signs_run_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_run_tiles_run_id'), table_name='run_tiles')
    op.drop_table('run_tiles')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
