"""street surveys

Revision ID: 492926dd170f
Revises: 3bfaae047841
Create Date: 2026-07-31 20:41:20.820033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '492926dd170f'
down_revision: Union[str, Sequence[str], None] = '3bfaae047841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('jobs', sa.Column('kind', sa.String(length=16), nullable=False, server_default='bbox'))
    op.add_column('jobs', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.add_column('jobs', sa.Column('buffer_m', sa.Integer(), nullable=False, server_default='25'))
    op.add_column('jobs', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # GeoAlchemy2 emits the GiST index as part of add_column for a Geometry
    # column, so creating it here as well fails with a duplicate relation.
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_column('jobs', 'geom')
    op.drop_column('jobs', 'buffer_m')
    op.drop_column('jobs', 'osm_id')
    op.drop_column('jobs', 'kind')
    op.drop_column('jobs', 'name')
    # ### end Alembic commands ###
