"""organisations

Revision ID: a6cdce74dbef
Revises: 79745d0884d6
Create Date: 2026-08-01 20:38:03.488117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cdce74dbef'
down_revision: Union[str, Sequence[str], None] = '79745d0884d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'organisations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organisations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_column('jobs', 'org_id')
    op.drop_table('organisations')
    # ### end Alembic commands ###
